package com.rfid.tracker.repository;

import com.rfid.tracker.entity.VerificationCode;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

@Repository
public interface VerificationCodeRepository extends JpaRepository<VerificationCode, Long> {

    // Find by code (for verification)
    Optional<VerificationCode> findByCode(String code);

    // Find by staff ID and section ID (to prevent duplicate codes for same period)
    Optional<VerificationCode> findByStaffIdAndSectionIdAndCodeEnteredCountGreaterThan(String staffId, String sectionId, Integer count);

    // Find all valid codes for a section on a specific date
    @Query("SELECT v FROM VerificationCode v WHERE v.sectionId = :sectionId AND DATE(v.generatedTime) = CURDATE() AND v.validUntil > CURRENT_TIMESTAMP")
    List<VerificationCode> findActiveCodesBySection(@Param("sectionId") String sectionId);

    // Find all codes generated by staff on a specific date
    @Query("SELECT v FROM VerificationCode v WHERE v.staffId = :staffId AND DATE(v.generatedTime) = CURDATE()")
    List<VerificationCode> findByStaffIdAndToday(@Param("staffId") String staffId);

    // Check if code exists and is still valid
    @Query("SELECT COUNT(v) > 0 FROM VerificationCode v WHERE v.code = :code AND v.validUntil > CURRENT_TIMESTAMP")
    boolean isCodeValidAndNotExpired(@Param("code") String code);

    // Find valid code by staff and section (current period)
    @Query("SELECT v FROM VerificationCode v WHERE v.staffId = :staffId AND v.sectionId = :sectionId AND v.validUntil > CURRENT_TIMESTAMP ORDER BY v.generatedTime DESC LIMIT 1")
    Optional<VerificationCode> findCurrentValidCode(@Param("staffId") String staffId, @Param("sectionId") String sectionId);

    // Count how many codes were generated for staff today
    @Query("SELECT COUNT(v) FROM VerificationCode v WHERE v.staffId = :staffId AND DATE(v.generatedTime) = CURDATE()")
    int countCodesGeneratedToday(@Param("staffId") String staffId);

    // Find expired codes (for cleanup)
    @Query("SELECT v FROM VerificationCode v WHERE v.validUntil < CURRENT_TIMESTAMP AND v.isUsed = FALSE")
    List<VerificationCode> findExpiredUnusedCodes();
}